---
replicaCount: 1
image:
  pullSecretName:
  app:
    name: ghcr.io/helldweller/apex-maps-notify-tgbot
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "50m"
        memory: "128Mi"
    env:
      - name: TGBOT_DEBUG
        value: "false"
      - name: LOG_LEVEL
        value: info
