# https://skaffold.dev/docs/references/yaml/
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: apex-maps-notify-tgbot
build:
  artifacts:
  - image: apex-maps-notify-tgbot
    ko:
      fromImage: alpine #golang:1.17-alpine
      dir: src/cmd/app
      dependencies:
        paths:
        - "src/*"
        - "skaffold/*"
        - "skaffold.yaml"
        ignore: []
profiles:
  - name: app
    deploy:
      kubectl:
        manifests:
          - skaffold/app.yaml
  - name: init
    deploy:
      # kubeContext: minikube
      kubectl:
        manifests:
          - skaffold/app-secret.yaml
          - skaffold/mongo.yaml
# portForward:
#   - resourceType: Service
#     resourceName: apex-maps-notify-tgbot
#     namespace: test
#     port: 8080
#     address: 127.0.0.1
#     localPort: 8080
