---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Release.Name }}
    spec:
      {{- if $.Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ $.Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: {{ $.Release.Name }}
          image: "{{ $.Values.image.app.name }}:{{ $.Chart.AppVersion | default "unknown" }}"
          {{- if $.Values.image.app.resources }}
          resources: {{ $.Values.image.app.resources | toYaml | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ $.Release.Name }}
          {{- if $.Values.image.app.env }}
          env: {{ $.Values.image.app.env | toYaml | nindent 12 }}
          {{- end }}
