# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: apex-maps-notify-tgbot
# spec:
#   type: ClusterIP
#   selector:
#     app: apex-maps-notify-tgbot
#   ports:
#     - port: 8080
#       targetPort: 8080
#       protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-maps-notify-tgbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apex-maps-notify-tgbot
  template:
    metadata:
      labels:
        app: apex-maps-notify-tgbot
    spec:
      containers:
        - name: app
          image: apex-maps-notify-tgbot
          resources: {}
          env:
            - name: TGBOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apex-maps-notify-tgbot
                  key: TGBOT_API_KEY
            - name: APEX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apex-maps-notify-tgbot
                  key: APEX_API_KEY
            # - name: MONGODB_URI
            #   valueFrom:
            #     secretKeyRef:
            #       name: apex-maps-notify-tgbot
            #       key: MONGODB_URI
            - name: TGBOT_DEBUG
              value: "false"
            - name: LOG_LEVEL
              value: info
