---
apiVersion: v1
kind: Pod
metadata:
  name: apex-maps-notify-tgbot
  labels:
    role: apex-maps-notify-tgbot
spec:
  containers:
    - name: app
      image: apex-maps-notify-tgbot
      resources: {}
      env:
        - name: TGBOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: apex-maps-notify-tgbot
              key: TGBOT_API_KEY
        - name: APEX_API_KEY
          valueFrom:
            secretKeyRef:
              name: apex-maps-notify-tgbot
              key: APEX_API_KEY
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: apex-maps-notify-tgbot
              key: MONGODB_URI
        - name: TGBOT_DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: error
 